vitaly-t/pg-promise

- lib/index.js
- test/streamSpec.js
Checking _reading is not correct, because
it will be set to true only if the stream
is in the flowing mode.  The stream consumer
may choose to use the stream in the paused mode,
and call the read() function to iterativelly
get each next result, in which case the check
will fail.
> Removed 'Stream not initialized' check

- typescript/pg-promise.d.ts
This will cause a compile error when used as a dependency on a project that uses the `noImplicitAny` compiler option
> Add explicit any type to callback parameter

- lib/utils/index.js
This bug was introduced with 9ea9385. Since Node interpreter don't have `process.argv[1]`, `path.dirname` would fail with the following error:
TypeError: Path must be a string. Received undefined
See: #158.
> fallback when run from Node interpreter.

- lib/formatting.js
this popped up on us because we use an object that's created similar to `Object.create(null)` as parameters with a QueryFile. since it has no constructor it was throwing an error `cannot read property 'name' of undefined`.
> make sure a constructor exists before attempting to check its name

- typescript/pg-promise.d.ts
Hi @vitaly-t 
Can we have IBaseProtocol, ITask, IConnected exposed under pgPromise namespace so we can import those interfaces in other modules?
Thanks!
> Expose IBaseProtocol, ITask, IConnected under pgPromise namespace

- typescript/pg-subset.d.ts
It seems to me that those two are switched, no? The function receives a `string` a can return `any` type, not the other way around, right?
Thanks
> setTypeParser typescript definition error

- jsdoc/style.css
Hello
When I scroll the doc I had this quite annoying scrollbar overriding text (under last Chrome) : 
Here is a PR to add a padding to avoid this : 
Thanks @vitaly-t for pg-promise.
> [Doc] Prevent scroll bar to override text

- lib/helpers/columnSet.js
This avoids the problem of `hasOwnProperty` and others not being defined when Object was created with `Object.create(null)`.
> Use `hasOwnProperty` from Object prototype

- typescript/pg-promise.d.ts
Instead of using `any` as a return type for `task()` or `tx()`, we can now specify a type or let typescript infer the type.
Screenshot of typings in production:
Typescript can correctly infer and validate types.
> types: added return type to task() and tx()

- typescript/pg-promise.d.ts
Changing the order of the IMain signatures so that the more
specific generic definitions can be inferred without casting
Due to how TS chooses matches for overloads the original ordering
causes the first overload to always be inferred by tsc, see
https://www.typescriptlang.org/docs/handbook/functions.html
With this change, you can now invoke the function and have the
inferred typing work correctly with all strict tsconfig.json
settings enabled and no casts, for example these
examples (taken from pg-promise-demo) now work as expected:
```js
const db: IDatabase<IExtensions> & IExtensions = pgp(config);
const db = <IDatabase<IExtensions> & IExtensions>pgp(config);
```
Before this change, these statements would not work with strict
tsconfig.json settings
> Changing the order of the IMain signature overloads

- typescript/pg-promise.d.ts
8.3.0 added the `schema` initOption: https://github.com/vitaly-t/pg-promise/releases/tag/v.8.3.0
This PR also adds it to the type definitions.
> Fix #507: add `schema` option to type definitions

- typescript/pg-promise.d.ts
Just a couple of cases where the TypeScript types were incomplete.
> Type improvements

- typescript/pg-promise.d.ts
Since `oneOrNone` can return null, it's probably more ergonomic to write `oneOrNone<{ foo: "bar" }>(...)` than `oneOrNone<{ foo: "bar"} | null>(...)`
> Tweak TypeScript return type for `oneOrNone`

- lib/cnContext.js
- lib/connect.js
Pg-promise doesn't propagate `err` to `disconnect` action, therefore, the connection in question becomes staled.
This PR aims to propagate the `err` to `disconnect` action, and hence `done(err)`. In that way, pool library can properly `release` and `remove` the client from the pool.
> Propagate client errors properly upon disconnect

- lib/queryFile.js
`!opt.minify` is always `false` so `!opt.minify !== 'after'` is always `true`. I think you meant to just test that `opt.minify` is not `'after'`
> fix: {minify: 'after'} was broken in queryFile

- lib/connect.js
- lib/database.js
- package.json
- test/db/header.js
- test/dbSpec.js
When an error is emitted by the pool, before pg-promise received the
client, the error handling failed with:
> TypeError: Cannot read property 'options' of undefined
Try to log pool errors best effort.
---
When an in-use client receives an error rely on the caller to end the
connection instead of doing it in the error handler to prevent releasing
the same connection twice.
Fixes https://github.com/vitaly-t/pg-promise/issues/599
Fixes https://github.com/vitaly-t/pg-promise/issues/600
Requires https://github.com/brianc/node-pg-pool/pull/123
> Fix error handling

- lib/utils/index.js
- test/dbSpec.js
Errors of the class 08 ("Connection Exceptions") don't trigger an attempted rollback if encountered during a transaction. This is usually the right idea, except in the case of '08P01', which is a protocol violation and means that the connection is still viable.
A particular instance which has bitten us, where users can trigger protocol violations, is when the user input contains unicode null bytes. After a connection has failed with this 08P01 error, it is tossed back into the connection pool without a rollback, and every subsequent user of that connection gets a "current transaction is aborted" error for every query (because the "begin transaction" statement doesn't even succeed).
This commit fixes that bug. Below is a reproduction. 
Repro:
```
const pgp = require('pg-promise')();
const …
```
> Fix protocol violations not resulting in a rollback

- typescript/README.MD
- typescript/pg-promise.d.ts
As of `pg-promise@9.0.2`, [dynamic protocol extensions](https://github.com/vitaly-t/pg-promise/blob/9.0.2/typescript/README.MD#with-extensions) are passed in pre-initialisation but typed post-initialisation. This can lead to mismatches between the supposed interface and the actual implementation:
```typescript
import pgPromise from 'pg-promise';
const options: pgPromise.IInitOptions<{ false: () => true }> = {
extend: obj => {
obj.false = () => true;
}
};
// pre-initialisation
const pgp = pgPromise(options as any);
// post-initialisation
const db = pgp<{ false: () => false }>({});
const result: false = db.false();
console.log(result);
// true
```
Also note the `as any` type assertion; pre-initialisation is awkward to work with when it is not parametric …
> Enable safer typing of extensions

- lib/query-file.js
In the example, `query` is only reference to the method that gets the string.
For docs it's more useful to call the function so it's actually the query as string.
> Clarify docs on how to get query as string from queryfile

- typescript/pg-promise.d.ts
The type definitions for `Column` do not include the `variable` accessor, so this adds it.
> Add `variable` to `Column` type definition

- .github/workflows/ci.yml
- README.md
- Adds badges to README
- Add [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) to Github Actions
- Postgres 14 and 15 support
> Run tests against Postgres 14 and 15

- lib/database.js
- lib/main.js
It's /apis/... not /api/...
I'm not sure how the github-pages bundling works, but there are dead links in the docs site (e.g. the `external:Result` link in https://vitaly-t.github.io/pg-promise/global.html#event:receive). I guessed that they come from these jsdoc comments.
> Fix node-postgres.com/apis/... links

- style.css
Hello, thank you for the wonderful repository.
I was viewing the documents using Chrome, but I fixed it because the scrollbar and text were overlapping.
I am using Chrome 123.
before
after
⚠️ This is my very first PR to this repository, so I might be missing something important.
> [docs] added margin to section
